# ── Backend dev ──────────────────────────────────────────────────────────────
FROM node:22-alpine AS backend-dev

# AJOUT : Installation d'OpenSSL pour Prisma
RUN apk add --no-cache openssl

WORKDIR /app/backend
COPY backend/package*.json ./
RUN npm install

COPY backend/ ./
RUN npx prisma generate

EXPOSE 3000

# ── Frontend dev ─────────────────────────────────────────────────────────────
FROM node:22-alpine AS frontend-dev

# AJOUT : Souvent utile pour les outils de build ou dépendances natives
RUN apk add --no-cache openssl

WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./

EXPOSE 5173